//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler
        ///
        ///end.
        /// </summary>
        public static string EnemyList {
            get {
                return ResourceManager.GetString("EnemyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triangle1
        ///119,155
        ///112,0
        ///224,232
        ///0,232
        ///triangle2
        ///119,155
        ///112,0
        ///224,232
        ///0,232
        ///triangle3
        ///119,155
        ///112,0
        ///224,232
        ///0,232
        ///pentagon1
        ///136,62
        ///117,0
        ///233,23
        ///188,61
        ///45,61
        ///0,23
        ///pentagon2
        ///136,62
        ///117,0
        ///233,23
        ///188,61
        ///45,61
        ///0,23
        ///floor1
        ///400,11
        ///0,0
        ///799,0
        ///799,22
        ///0,22
        ///tfloor
        ///400,63
        ///0,0
        ///799,00	
        ///799,126
        ///0,126
        ///twall
        ///63,400
        ///0,0
        ///126,0
        ///126,799
        ///0,799
        ///floorbythedoor
        ///175,10
        ///0,0
        ///350,0
        ///350,20
        ///0,20
        ///floorhump
        ///314,49
        ///134,0
        ///494,0
        ///630,90
        ///0,90
        ///longfloor
        ///490,10
        ///0,0
        ///980,0
        ///980,20
        ///0,20
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shapeList {
            get {
                return ResourceManager.GetString("shapeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triangle2
        ///400,300
        ///triangle1
        ///400,-100
        ///triangle3
        ///500,600
        ///pentagon1
        ///136,39
        ///pentagon2
        ///300,300
        ///floor1
        ///400, 250
        ///tfloor1
        ///400,500
        ///tfloor2
        ///400,-23
        ///twall1
        ///-10,240
        ///twall2
        ///810,240
        ///floorbythedoor
        ///500,200
        ///floorhump
        ///50,150
        ///longfloor1
        ///-710,200
        ///longfloor2
        ///-1880,330
        ///mramp
        ///-1330,265
        ///hwall1
        ///665,90
        ///hwall2
        ///-2380,230
        ///.
        /// </summary>
        public static string shapeplace {
            get {
                return ResourceManager.GetString("shapeplace", resourceCulture);
            }
        }
    }
}
